services:
  - type: web
    name: flask-face-recognition-api
    env: docker
    plan: free
    branch: main  # or your default Git branch
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: uploads
